from typing import Any, Dict, List, Optional, Protocol
from app.schemas.entities import BaseEntity
from app.schemas.graph import GraphDataResponse

class M3GraphDataServiceProtocol(Protocol):
    async def get_node_by_id(self, node_id: str) -> Optional[Dict[str, Any]]: ...
    async def query_entities(self, entity_type: Optional[str] = None, limit: int = 50) -> List[Dict[str, Any]]: ...
    async def get_neighborhood(self, node_id: str, hops: int = 1) -> GraphDataResponse: ...
    async def get_subgraph(self, node_ids: List[str]) -> GraphDataResponse: ...

class M4AiNlpServiceProtocol(Protocol):
    async def extract_from_document(self, file_bytes: bytes, file_name: str, doc_type: str) -> Dict[str, Any]: ...
    async def answer_grounded_question(self, question: str, case_id: Optional[str] = None) -> Dict[str, Any]: ...

class M5GraphAnalyticsServiceProtocol(Protocol):
    async def find_shortest_path(self, source_id: str, target_id: str, max_depth: int = 6) -> Dict[str, Any]: ...
    async def multi_hop_search(self, start_id: str, target_type: str, max_hops: int = 3) -> Dict[str, Any]: ...
    async def detect_anomalies(self, case_id: Optional[str] = None) -> List[Dict[str, Any]]: ...

class M6SecurityServiceProtocol(Protocol):
    async def verify_token(self, token: str) -> Optional[Any]: ...
    async def log_audit_event(self, event: Dict[str, Any]) -> bool: ...
    async def verify_evidence_integrity(self, evidence_id: str) -> Dict[str, Any]: ...
    async def get_bsa_section_65b_certificate(self, evidence_id: str) -> Dict[str, Any]: ...
