FROM python:3.11-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV PYTHONPATH /app

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

COPY member2_backend/requirements.txt ./member2_backend/
COPY member3_data_graph/requirements.txt ./member3_data_graph/
COPY member4_ai_nlp/requirements.txt ./member4_ai_nlp/

RUN pip install --no-cache-dir -r member2_backend/requirements.txt -r member3_data_graph/requirements.txt -r member4_ai_nlp/requirements.txt networkx

COPY . .

WORKDIR /app/member2_backend
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
